
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module term_project(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================
main(.fpgaclk(CLOCK2_50),.hsync(VGA_HS),
.vsync(VGA_VS),
.red(VGA_R),.green(VGA_G),
.blue(VGA_B),
.sync(VGA_SYNC_N),
.clk(VGA_CLK),
.blank(VGA_BLANK_N),
.btn_right(KEY[0]),
.btn_left(KEY[1]),
.sw_shooting_mode2(SW[0]),
.sw_shooting_mode1(SW[1]),
.btn_fire(KEY[2]),
.level2(SW[3:2]),
.reset_game(SW[9]),
.segments1(HEX0[6:0]),
.segments2(HEX1[6:0]),
.shooting_led(LEDR[2:0]),
.background_switch(SW[8])
);


endmodule



